### ISSUE TITLE
How can I know that if the face in the picture is a spoof face?

### ISSUE THREAD

**Issue by Wisgon** [InnovativeCoder/Variational_retinex_based_model#1]
Thanks for the job,first.
I had run your run.py and put an image of spoof face in the "data" folder, and I got 4 windows of the same image but they look a little different, so how can I make a judge that the face in the image is spoof or not spoof?

**Comment by Wisgon** [comment]
@InnovativeCoder

**Comment by InnovativeCoder** [comment]
Sorry for that, I did'nt see the issue earlier, this project is bit old, now nobody uses this retinex approach. With rise in computation power and new methods of performing deep learning, we can easily catch spoof or not spoof using neural networks. You can search for papers which use this approach and then built your own neural network.

**Comment by Wisgon** [comment]
Ok, Thank you anyway!
